# Generated by Django 3.0.3 on 2020-02-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_auto_20200225_1106'),
        ('customers', '0002_remove_myprofile_favourite_snack'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateField()),
                ('return_date', models.DateField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customers.MyProfile')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies.Movie')),
            ],
        ),
    ]
