# Generated by Django 3.0.3 on 2020-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierent',
            name='reserve_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movierent',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
