# Generated by Django 3.0.3 on 2020-03-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200302_1443'),
        ('movierent', '0002_auto_20200227_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierent',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='movies.Movie'),
        ),
    ]
