# Generated by Django 3.0.3 on 2020-02-25 08:00

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='label')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('length', models.TimeField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('release_date', models.DateField()),
                ('rented', models.BooleanField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title')),
                ('synopsis', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('trailer_url', models.URLField()),
                ('movie_genres', models.ManyToManyField(to='movies.MovieGenre')),
            ],
        ),
    ]
