# Generated by Django 3.0.3 on 2020-02-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rented',
        ),
    ]
