# Generated by Django 3.0.3 on 2020-03-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200302_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='slug_en',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slug_fr',
        ),
    ]
