# Generated by Django 3.0.3 on 2020-03-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200302_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieGenreTranslation',
        ),
        migrations.AlterModelOptions(
            name='moviegenre',
            options={},
        ),
        migrations.RenameField(
            model_name='moviegenre',
            old_name='slug_en',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='label_fr',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='slug_fr',
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='label',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
